
=head0 The Comprehensive Perl Archive Network

X<CPAN>
The Comprehensive Perl Archive Network, known as CPAN is an archive of
Perl applications, modules and frameworks. It is named after another
archive, The Comprehensive TeX Archive Network, an archive of TeX and
LaTeX modules and styles.

CPAN is an Archive of Perl stuff, it is available throught the Network
and is Comprehensive, in the sense that it is a large collection, but
also that it includes nearly all developed modules, and they are
available in an organized way.

Note that CPAN does not have any kind of guarantee that the available
modules are not malicious, or that provides the documented
features. Therefore, knowing what modules are being used by the
community is great, as it gives information about their quality and
trust.

CPAN is available from L<http://cpan.org/> or one of the hundreds of
available mirror. You can access the modules using C<FTP> or, more
interesting, using the search feature of CPAN. It will give you
information on the module author, what the latest version is, points
to the download file, gives you access to the module documentation and
a rating system, where users can rate modules.

There are a bunch of other web sites that were developed to make the
CPAN experience more rich. There are some of them:

=over

=item B<AnnoCPAN>

X<CPAN, AnnoCPAN>
AnnoCPAN (L<http://www.annocpan.org>) gives you access to modules
documentation, but also to annotations over that documentation. What
this means, is that any user can annotate the documentation with
further information, incoherences and other (relevant) information.

=item B<CPAN Forum>

X<CPAN, Forum>
CPAN Forum (L<http://cpanforum.com/>) offers a forum for each
module. Some authors maintain their forum active, some others do not
use them. Some others, prefer to create forums in other web sites, or
to create mailing lists.

=item B<CPAN Testers>

X<CPAN, Testers>
CPAN Testers (L<http://static.cpantesters.org/>) gives information
about how each module installs, and how their tests pass or fail in
different architectures. When installing a module, if the build fails,
this web site can be used to detect whether it is a local fail, or a
known bug. For module developers it is useful to check if modules are
portable and if tests pass.

=back

=head1 Installing CPAN Modules

X<Module, installing>
There are two main different ways to install a module from CPAN: using
an automated installation tool, like C<cpan>, C<cpanp> or C<cpanm>, or
installing manually. The main difference is that the automated
approach fetches the module from CPAN, calculates its dependencies and
install them. When installing manually, you will need to follow the
non installed dependencies by yourself.

=head2 *Using C<cpan>

X<Command, cpan>X<cpan>
The command line tool C<cpan> ships with Perl, and can be described as
the official tool to install modules. The only situations whether you
probably do not have C<cpan> installed in your system are derived of
using ActiveState ActivePerl (in this case read the section on
C<PPM>), or using a Linux distribution that splits the Perl package in
smaller packages. In this case use your package system and search for
the C<cpan> package.

Usually you want to run C<cpan> as a system administrator, so you have
the needed permissions to write into the system tree. Recent C<cpan>
versions have an automated configuring system. Nevertheless, if you
run C<cpan> and it asks a lot of questions, you are safe on choosing
the default answers. Just take care of choosing a nearby mirror, so
packages download faster.

C<cpan> can be used from the command line issuing:

    cpan Module::Name Another::Module

This will install in your system the two modules C<Module::Name> and
C<Another::Module>. The other approach is using C<cpan> shell. For
that, just type C<cpan> in your command line, and a C<cpan> shell will
appear. You can get help on the C<cpan> shell commands using C<h>. To
install modules use the C<i> command.

=begin screen

 cpan shell -- CPAN exploration and modules installation
 Enter 'h' for help.
  
 cpan[1]> i Module::Name Another::Module

=end screen

=head2 *Using C<cpanp>

X<Command, cpanp>X<cpanp>X<Module, CPANPLUS>
C<cpanp> is the command line tool to the C<CPANPLUS> module, that
enhances the C<CPAN> module used by C<cpan> with some new
functionalities. Although some C<cpanp> commands differ from the ones
available on C<cpan>, the basic behavior is similar. To install from
the command line add the C<-i> switch:

    cpanp -i Module::Name Another::Module

For the interactive shell, C<cpanp> also uses the C<i> command.

=head2 *Using C<cpanm>

X<Command, cpanm>X<cpanm>

=head2 *ActivePerl PPM

X<PPM>X<ActivePerl>

=head2 *Manual Install

X<Module, manual installation>

=cut

## Local Variables:
##  ispell-local-dictionary: "english"
##  mode: flyspell
## End:
