
=head0 Modern Perl OO

=head1 Moo

=begin CPANinfo

B<Documented version:> 0.009008

B<CPAN:> L<http://search.cpan.org/dist/Moo>

=end CPANinfo

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus
sodales pellentesque lectus. Nam sed augue magna, eget gravida
nulla. Aenean vitae augue id orci dignissim pellentesque. Quisque vel
nunc arcu. Quisque pharetra convallis diam eu condimentum. Etiam ipsum
diam, cursus sit amet mollis quis, lobortis dignissim risus. Duis
bibendum facilisis tellus eget ornare. Suspendisse vestibulum, neque
et blandit mattis, tortor eros cursus odio, et aliquam ligula est
imperdiet turpis. Vivamus purus lorem, sodales ut hendrerit quis,
adipiscing in justo. Mauris volutpat metus eget sapien rhoncus
pellentesque. Nunc in ligula id nibh dapibus aliquet. Proin tempus,
nunc tincidunt fringilla sodales, ante erat accumsan ipsum, quis
pretium tortor dui nec velit. Fusce dapibus, erat eget rhoncus
elementum, turpis tortor aliquam risus, quis porta felis est auctor
odio. Suspendisse eu odio non felis vehicula tempus nec sed
turpis. Nullam aliquet lacus eu ligula interdum sit amet pulvinar ante
faucibus.

=head1 Mouse

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus
sodales pellentesque lectus. Nam sed augue magna, eget gravida
nulla. Aenean vitae augue id orci dignissim pellentesque. Quisque vel
nunc arcu. Quisque pharetra convallis diam eu condimentum. Etiam ipsum
diam, cursus sit amet mollis quis, lobortis dignissim risus. Duis
bibendum facilisis tellus eget ornare. Suspendisse vestibulum, neque
et blandit mattis, tortor eros cursus odio, et aliquam ligula est
imperdiet turpis. Vivamus purus lorem, sodales ut hendrerit quis,
adipiscing in justo. Mauris volutpat metus eget sapien rhoncus
pellentesque. Nunc in ligula id nibh dapibus aliquet. Proin tempus,
nunc tincidunt fringilla sodales, ante erat accumsan ipsum, quis
pretium tortor dui nec velit. Fusce dapibus, erat eget rhoncus
elementum, turpis tortor aliquam risus, quis porta felis est auctor
odio. Suspendisse eu odio non felis vehicula tempus nec sed
turpis. Nullam aliquet lacus eu ligula interdum sit amet pulvinar ante
faucibus.

=head1 Moose


Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus
sodales pellentesque lectus. Nam sed augue magna, eget gravida
nulla. Aenean vitae augue id orci dignissim pellentesque. Quisque vel
nunc arcu. Quisque pharetra convallis diam eu condimentum. Etiam ipsum
diam, cursus sit amet mollis quis, lobortis dignissim risus. Duis
bibendum facilisis tellus eget ornare. Suspendisse vestibulum, neque
et blandit mattis, tortor eros cursus odio, et aliquam ligula est
imperdiet turpis. Vivamus purus lorem, sodales ut hendrerit quis,
adipiscing in justo. Mauris volutpat metus eget sapien rhoncus
pellentesque. Nunc in ligula id nibh dapibus aliquet. Proin tempus,
nunc tincidunt fringilla sodales, ante erat accumsan ipsum, quis
pretium tortor dui nec velit. Fusce dapibus, erat eget rhoncus
elementum, turpis tortor aliquam risus, quis porta felis est auctor
odio. Suspendisse eu odio non felis vehicula tempus nec sed
turpis. Nullam aliquet lacus eu ligula interdum sit amet pulvinar ante
faucibus.

=cut

## Local Variables:
##  ispell-local-dictionary: "english"
##  mode: flyspell
## End:

